### PR TITLE
Add DesktopGameAnalytics

### PR DESCRIPTION
**Pull request by yuraj11**

### CODE REVIEW

**Review by MrStahlfelge — CHANGES_REQUESTED** [review]
`DesktopGameAnalytics` look good. However your changes make the project unuseable for projects based on libGDX <= 1.9.8, and Gradle >= 3.3 is also not supported for all platforms so far.

What are the changes to `gradlew` are for?

**Comment by yuraj11** [comment]
Gradle was updated using https://gradle.org/install/#with-the-gradle-wrapper `gradlew wrapper` It also updates gradlew scripts.
And about the versions - that's not an issue because gradle will pick latest versions of library and you can always force to use old dependency ( https://gist.github.com/cr7pt0gr4ph7/6cd6339eabc2056bc3e7 ). Is there any reason why you would not update to latest versions? At least gradle 4.x works fine with libgdx and I don't see any reason to use old version.

**Comment by MrStahlfelge** [comment]
Yes, there are reasons why not to use the latest libGDX versions if you have a game that's tested with an older version. :) With my own projects I am on 1.9.8 because 1.9.9 has introduced some bugs. 
As you said, Gradle will pick the latest version of all declared dependencies. So if this lib declares 1.9.9, it will force every game using this lib also to use at least 1.9.9. by declaring an older version here it is documented that this lib also can be used with older versions (and it does work with them without problems).

About the Gradle update: one change should be made at a time, and adding the DesktopAnalytics implementation is not related to a Gradle update. 

When changing the Gradle version, I have to test if the lib will still work in older projects using an older Gradle version. Chance is that it does not work anymore for Android or GWT builds, and there's no advantage gained by updating at the moment. You are right that 4.6 is used for libGDX 19.10 at the moment, so it is a good choice, but I can only merge it after making sure that it doesn't cause any problems for dependant projects still being on 3.3.

**Comment by yuraj11** [comment]
Ok no problem. I have reverted those changes.

**Comment by MrStahlfelge** [comment]
Thanks, merged manually because of conflict with artifact version change.

**Pull request closed without merging**
