### PR TITLE
Updated gradle project, lib versions

### PR DESCRIPTION
**Pull request by piotr-j**

### CODE REVIEW

**Comment by piotr-j** [comment]
Seems travis doesnt like updated sdk, dunno how to fix it.

**Comment by piotr-j** [comment]
Not sure what do do about build failing :/

**Comment by MrStahlfelge** [comment]
What is the point in having this change? If this would get merged, the lib is not useable with older gdx versions any more while at the moment it is useable with everything from 1.9.5 on.

**Comment by piotr-j** [comment]
Just updated everything that was whining at me. Gdx version could certainly be skipped.

**Comment by MrStahlfelge** [comment]
Closing this because it does not build and there's no benefit in the updates for the moment.

**Pull request closed without merging**
